version: '3.8'
services:
  redis:
    image: redis
    container_name: redis_api
    ports:
      - "6379:6379"
  database:
    image: mysql:latest
    container_name: databaseContainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Kurlar
    ports:
      - "3307:3306"
  dataapi:
    image: data-api-last
    container_name: dataapi
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
      - "8082:443"
  businessapi:
    image: business-api-last
    container_name: businessapi
    restart: always
    depends_on:
      - redis,
    ports:
      - "8083:80"
      - "8084:443"
  website:
    image: website-last
    container_name: website
    restart: always
    depends_on:
      - businessapi
    ports:
      - "8085:80"
      - "8086:443"


